project/app/urls.py
from django.urls import path, re_path, include

from . import views

urlpatterns = [
    re_path(r'^(?P<country_code>[a-z]{2})/$', views.index, name='index'),
    re_path(r'^(?P<country_code>[a-z]{2})/product/(?P<product_slug>[-a-zA-Z0-9_]+)$', views.product, name='product'),
    re_path(r'^(?P<country_code>[a-z]{2})/products$', views.products, name='products'),
    re_path(r'^(?P<country_code>[a-z]{2})/brands/$', views.Brands.as_view(), name='brands'),
    re_path(r'^(?P<country_code>[a-z]{2})/categories/$', views.Categories.as_view(), name='categories'),
    re_path(r'^(?P<country_code>[a-z]{2})/top/(?P<category_slug>[-a-zA-Z0-9_]+)/(?P<category_filter>[-a-zA-Z0-9_]+)/$', views.top, name='top'),
    re_path(r'^(?P<country_code>[a-z]{2})/login/$', views.CustomLoginView.as_view(), name='login'),
    re_path(r'^(?P<country_code>[a-z]{2})/signup/$', views.signup, name='signup'),
    re_path(r'^(?P<country_code>[a-z]{2})/profile/(?P<username>[-a-zA-Z0-9_]+)$', views.profile, name='profile'),
    re_path(r'^(?P<country_code>[a-z]{2})/edit-profile/$', views.edit_profile, name='edit_profile'),
    path('accounts/', include('django.contrib.auth.urls')),
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/app/models.py
from datetime import datetime

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Count
from django.utils.text import slugify
from stdimage import StdImageField


# TODO add model for data source


class Country(models.Model):
    class Meta:
        verbose_name_plural = 'countries'

    code = models.CharField(max_length=2, unique=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Currency(models.Model):
    class Meta:
        verbose_name_plural = 'currencies'

    iso_code = models.CharField(max_length=3, unique=True)
    symbol = models.CharField(max_length=1)

    def __str__(self):
        return self.iso_code


class CustomUser(AbstractUser):
    # TODO remove last name field?
    email = models.EmailField(verbose_name='email address', max_length=255, unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def save(self, *args, **kwargs):
        is_new_user = self._state.adding
        super().save(*args, **kwargs)
        # Create Profile on creation of CustomUser.
        # Overriding save() instead of using signals: https://lincolnloop.com/blog/django-anti-patterns-signals/
        if is_new_user:
            profile = Profile(user=self)
            profile.save()


class Profile(models.Model):
    NOT_SPECIFIED = 'N'
    blank_choice = [(None, '---------')]
    BIRTH_YEAR_CHOICES = [(r, str(r)) for r in reversed(range(datetime.today().year - 100, datetime.today().year - 13))]  # No kids allowed

    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = [(MALE, 'Male'),
                      (FEMALE, 'Female'),
                      (NOT_SPECIFIED, 'Prefer not to say')]
    # skin_type
    DRY = 'dry'
    NORMAL = 'normal'
    OILY = 'oily'
    COMBINATION = 'combination'
    SENSITIVE = 'sensitive'
    SKIN_TYPE_CODES = [DRY, NORMAL, OILY, COMBINATION, SENSITIVE, NOT_SPECIFIED]
    SKIN_TYPE_CHOICES = [(DRY, 'Dry'),
                         (NORMAL, 'Normal'),
                         (OILY, 'Oily'),
                         (COMBINATION, 'Combination'),
                         (SENSITIVE, 'Sensitive'),
                         (NOT_SPECIFIED, 'Prefer not to say')]

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # Allowing all of these fields to be blank so we can create a record in Profile when saving the CustomUser model:
    country = models.ForeignKey(Country, on_delete=models.PROTECT, blank=True, null=True)
    birth_year = models.PositiveSmallIntegerField(choices=BIRTH_YEAR_CHOICES, blank=True, null=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, null=True)
    skin_type = models.CharField(max_length=11, choices=SKIN_TYPE_CHOICES, blank=True)


class Category(models.Model):
    class Meta:
        verbose_name_plural = 'categories'
        ordering = ["-name"]

    name = models.CharField(max_length=50, unique=True)
    name_slug = models.SlugField(max_length=50)

    filter_type = models.CharField(max_length=4, choices=[('skin', 'Skin Type')], blank=True)

    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.name)   # Note this will break URLs
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class BrandParent(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Peta(models.Model):
    valid_from = models.DateField()
    valid_to = models.DateField(blank=True, null=True)
    company_name = models.CharField(max_length=100)
    peta_logo = models.BooleanField(null=True, blank=True)
    vegan_notes = models.CharField(max_length=300, blank=True)
    vegan = models.BooleanField(null=True, blank=True)
    testing_policy = models.BooleanField(null=True, blank=True)

    def __str__(self):
        return ' | '.join([self.company_name, str(self.testing_policy)])


class Brand(models.Model):
    name = models.CharField(max_length=50, unique=True)
    name_slug = models.SlugField(max_length=50)

    parent = models.ForeignKey(BrandParent, on_delete=models.PROTECT, null=True, blank=True)
    peta = models.ForeignKey(Peta, on_delete=models.SET_NULL, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.name)   # Note this will break URLs
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Product(models.Model):
    # Note product sharing same name:
    # Face & Stubble Care Kit by Percy Nobleman, A Men's Gift Set For Skin Care. Moisturiser, Wash and Face Towel Kit
    name = models.CharField(max_length=200)
    name_slug = models.SlugField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)

    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, blank=True, null=True)
    ingredients = models.CharField(max_length=1000, blank=True)
    description = models.CharField(max_length=1000, blank=True)
    directions = models.CharField(max_length=1000, blank=True)
    volume_ml = models.PositiveSmallIntegerField(blank=True, null=True)  # TODO What if a product can have different sizes?
    made_in = models.ForeignKey(Country, on_delete=models.PROTECT, blank=True, null=True)  # Assumes product is only made in one country
    std_image = StdImageField(
        upload_to='product_images/',
        variations={'small': {"width": 125, "height": 250}},
        delete_orphans=True,
        blank=True
    )

    users_using_count = models.PositiveSmallIntegerField(default=0)

    def users_using_rank(self):
        rank = Product.objects.filter(users_using_count__gt=self.users_using_count).count() + 1
        return rank

    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.name)   # Note this will break URLs
        super().save(*args, **kwargs)

    def __str__(self):
        if self.brand:
            return ' | '.join([self.brand.name, self.name])
        else:
            return self.name


class Retailer(models.Model):
    name = models.CharField(max_length=50, unique=True)
    country = models.ForeignKey(Country, on_delete=models.PROTECT)
    currency = models.ForeignKey(Currency, on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class RetailerProduct(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, on_delete=models.SET_NULL)
    retailer = models.ForeignKey(Retailer, on_delete=models.PROTECT)
    category = models.CharField(max_length=100)
    name = models.CharField(max_length=500)
    url = models.URLField()
    is_for_women = models.BooleanField()
    is_multipack = models.BooleanField()

    brand = models.CharField(max_length=200, blank=True)
    manufacturer = models.CharField(max_length=200, blank=True)
    ingredients = models.CharField(max_length=1000, blank=True)
    description = models.CharField(max_length=1000, blank=True)
    directions = models.CharField(max_length=1000, blank=True)
    volume_ml = models.PositiveSmallIntegerField(blank=True, null=True)
    gender = models.CharField(max_length=100, blank=True)
    country_of_origin = models.CharField(max_length=100, blank=True)
    identifier = models.CharField(max_length=10, blank=True)
    rating_average = models.PositiveSmallIntegerField(blank=True, null=True)
    rating_count = models.PositiveSmallIntegerField(blank=True, null=True)
    last_updated = models.DateTimeField(auto_now=True)
    # updated_by = models.CharField(max_length=10, blank=True)
    # when_entered = models.DateTimeField(auto_now=True)
    # entered_by = models.CharField(max_length=10)
    std_image = StdImageField(
        upload_to='retailer_product_images/',
        variations={'small': {"width": 125, "height": 250}},
        delete_orphans=True,
        blank=True
    )

    def __str__(self):
        return ' | '.join([self.retailer.name, self.name])

    # TODO If volume_ml is updated, we should update price_per_ml in Price


class Price(models.Model):
    retailer_product = models.OneToOneField(RetailerProduct, on_delete=models.CASCADE)
    price = models.FloatField(validators=[MinValueValidator(0.0)])
    last_updated = models.DateTimeField(auto_now=True)
    # updated_by = models.CharField(max_length=10)
    price_per_100_ml = models.FloatField(validators=[MinValueValidator(0.0)], blank=True, null=True)
    # TODO store price history?

    def save(self, *args, **kwargs):
        if self.retailer_product.volume_ml:
            self.price_per_100_ml = round(self.price / self.retailer_product.volume_ml * 100.0, 2)
        super().save(*args, **kwargs)

    def __str__(self):
        return ' | '.join([self.retailer_product.retailer.name, self.retailer_product.brand, self.retailer_product.name, str(self.price), self.retailer_product.retailer.currency.iso_code])


class Review(models.Model):
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['product', 'user'], name='unique_review')
        ]

    RATING_CHOICES = [
        (1, "Don't like it"),
        (2, "It's OK"),
        (3, 'Like it'),
        (4, 'Really like it'),
        (5, "It's amazing")
    ]

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=RATING_CHOICES)
    review = models.CharField(max_length=1000, blank=True)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return ' | '.join([self.product.name, self.user.email])


class UserActivity(models.Model):
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['product', 'user'], name='unique_activity')
        ]
        verbose_name_plural = 'user activity'

    BLANK = ''

project/app/templates/app/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/style.css' %}">
    {# icons are from https://icons.getbootstrap.com/ #}
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Playfair+Display:wght@500;600;800&display=swap" rel="stylesheet">

    <title>{% block title %}The Best Mens{% endblock %}</title>
</head>
<body>
<div class="d-flex flex-column sticky-footer-wrapper">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' country_code %}">TheBestMens <small class="text-muted" id="country-code">{{ country_code|upper }}</small></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07"
                aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExample07">
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                {% url 'index' country_code as index_url %}
                <li class="nav-item {% if request.path == index_url %}active{% endif %}">
                    <a class="nav-link"{% if request.path == index_url %} aria-current="page" {% endif %} href="{{ index_url }}">HOME</a>
                </li>

                {% url 'products' country_code=country_code as products_url %}
                <li class="nav-item dropdown {% if request.path == products_url %}active{% endif %}">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-expanded="false" {% if request.path == products_url %} aria-current="page" {% endif %}>PRODUCTS</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown09">
                        <li><a class="dropdown-item" href="{{ products_url }}">All</a></li>
                        {% for nav_category in nav_categories %}
                            <li><a class="dropdown-item" href="{{ products_url }}?category={{ nav_category.id }}">{{ nav_category.name }}</a></li>
                            {% endfor %}
                    </ul>
                </li>
            </ul>

            <div>
                <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
                     {% if user.is_authenticated %}
                            {% url 'profile' username=user.username country_code=country_code as view_profile_url%}
                            {% url 'edit_profile' country_code as edit_profile_url%}
                    <li class="nav-item dropdown {% if request.path == view_profile_url or request.path == edit_profile_url  or request.path == reviews_url %}active{% endif %}">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown07" data-toggle="dropdown" aria-expanded="false">MY ACCOUNT</a>
                        <ul class="dropdown-menu" aria-labelledby="dropdown07">
                            <li><a class="dropdown-item {% if request.path == view_profile_url  %}active{% endif %}" href="{{ view_profile_url }}" {% if request.path == edit_profile_url %} aria-current="page" {% endif %}>VIEW PROFILE</a></li>
                            <li><a class="dropdown-item {% if request.path == edit_profile_url  %}active{% endif %}" href="{{ edit_profile_url }}" {% if request.path == edit_profile_url %} aria-current="page" {% endif %}>EDIT PROFILE</a></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}?next={% url 'index' country_code %}">LOG OUT {% include 'app/svg/box-arrow-right.svg' %}</a></li>
                        </ul>
                    </li>
                    {% else %}
                    {% url 'signup' country_code as signup_url %}
                    <li class="nav-item {% if request.path == signup_url  %}active{% endif %}">
                        <a class="nav-link" {% if request.path == signup_url %} aria-current="page" {% endif %} href="{{ signup_url }}">SIGN UP {% include 'app/svg/person-plus.svg' %}</a>
                    </li>
                    {% url 'login' country_code as login_url %}
                    <li class="nav-item {% if request.path == login_url  %}active{% endif %}">
                        <a class="nav-link" {% if request.path == login_url %} aria-current="page" {% endif %} href="{{ login_url }}?next={{ request.path }}">LOG IN {% include 'app/svg/box-arrow-in-right.svg' %}</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>


<main class="flex-fill">
<div class="container">
    {% block content %}{% endblock %}
</div>
</main>

<footer class="footer mt-auto py-3 bg-light">

  <div class="container text-center text-muted">
      As an Amazon Associate I earn from qualifying purchases.<br />
      Looking for something that's not listed or have a question? Email me at <a href="mailto:nzwade@gmail.com">nzwade@gmail.com</a>
  </div>
</footer>

</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<script type = "text/javascript">
        $(function () {
          $('[data-toggle="tooltip"]').tooltip()
        })
    </script>

</body>
</html>

project/app/templates/app/brand_peta.html
{% if brand.peta %}
<li>PETA Cruelty free? {% include 'app/icons/animal_testing.html' %}</li>
<li>PETA Vegan? {% include 'app/icons/vegan.html' %}</li>
{% else %}
<li>PETA Cruelty free? {% include 'app/icons/animal_testing.html' %}</li>
<li>PETA Vegan? {% include 'app/icons/vegan.html' %}</li>
{% endif %}

project/app/templates/app/brands.html
{% extends "app/base.html" %}

{% block content %}
<h1>Brands</h1>

<table class="table table-hover">
    <thead>
    <tr>
        <th scope="col">Parent Company</th>
        <th scope="col">Brand</th>
        <th scope="col">PETA Cruelty free?</th>
        <th scope="col">PETA Vegan?</th>
    </tr>
    </thead>
    <tbody>
    {% for brand in brands %}
    <tr>
        <td>{{ brand.parent.name }}</td>
        <td><a href="{% url 'brand' country_code=country_code brand_slug=brand.name_slug %}">{{ brand.name }}</a></td>
        <td>
            {% include 'app/icons/animal_testing.html' %}
        </td>
        <td>
            {% include 'app/icons/vegan.html' %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<p>{{ brands.count }} brand{{ brands.count|pluralize }}.</p>

{% endblock content %}

project/app/templates/app/categories.html
{% extends "app/base.html" %}

{% block content %}
<h1>Categories</h1>

<table class="table">
  <thead>
    <tr>
        <th scope="col">Category</th>
        <th scope="col">Best Products</th>
    </tr>
  </thead>
  <tbody>
  {% for category in categories %}
    <tr>
      <td><a href="{% url 'category' country_code=country_code category_slug=category.name_slug %}">
          {{ category.name }}</a></td>
        <td>
            {% include 'app/filter_buttons.html' %}
        </td>
    </tr>
  {% endfor %}
  </tbody>
</table>

<p>{{ categories.count }} categor{{ categories.count|pluralize:"y,ies" }}.</p>

{% endblock content %}

project/app/templates/app/edit_profile.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Edit Profile</h1>
<hr />
<div class="row row-fluid justify-content-center">
    <div class="col-sm-9">
        {% if form_message %}
        <div class="alert alert-success" role="alert">{{ form_message }}</div>
        {% endif %}
        <form action="{% url 'edit_profile' country_code %}" method="post">
            {% crispy user_form %}
            {% crispy profile_form %}
            {# if user has come from another page and we have next in our context then redirect the user back there #}
            {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
            {% else %}
            <input type="hidden" name="next" value="{% url 'index' country_code %}">
            {% endif %}
            <button type="submit" class="btn btn-success">Save</button>
            <!--      <button type="button" class="btn btn-secondary">Forgotten password?</button>-->
        </form>
    </div>
</div>
{% endblock content %}

project/app/templates/app/filter_buttons.html
<div class="btn-group" role="group" aria-label="Basic example">
 {% if category.filter_type %}
  <button type="button" class="btn btn-sm btn-outline-primary disabled" aria-disabled="true">{{ category.get_filter_type_display }}</button>
 {% endif %}

 {% url 'top' country_code=country_code category_slug=category.name_slug category_filter='all' as all_url %}
 <a href="{{ all_url }}" role="button" class="btn btn-sm btn-outline-primary {% if request.path == all_url %}active{% endif %}">All</a>

 {% if category.filter_type == 'skin' %}
  {% for skin_type_code, skin_type_name in skin_type_choices.items %}
   {% url 'top' country_code=country_code category_slug=category.name_slug category_filter=skin_type_code as category_url %}
   <a href="{{ category_url }}" role="button" class="btn btn-sm btn-outline-primary {% if request.path == category_url %}active{% endif %}">{{ skin_type_name }}</a>
  {% endfor %}
 {% endif %}
</div>

project/app/templates/app/login.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Log In</h1>
<div class="row row-fluid justify-content-center">
  <div class="col-sm-7">
    <form action="{% url 'login' country_code=country_code %}" method="post">
      {% crispy form %}
      {# if user has come from another page and we have next in our context then redirect the user back there #}
      {% if next %}
      <input type="hidden" name="next" value="{{ next }}">
      {% else %}
      <input type="hidden" name="next" value="{% url 'index' country_code=country_code %}">
      {% endif %}
      <button type="submit" class="btn btn-success">Log In</button>
<!--      <button type="button" class="btn btn-secondary">Forgotten password?</button>-->
    </form>
  </div>
</div>
{% endblock content %}

project/app/templates/app/product.html
{% extends "app/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %} <!-- for ordinal tag !-->

{% block content %}
<h1>{% if product.brand %}<small class="text-muted">{{ product.brand.name }}</small> {% endif %}{{ product.name }}</h1>

<div class="row row-fluid">

</div>

<div class="row row-fluid">
    {% include 'app/product_summary.html' %}
    <div class="col-md-9">
        <h5>{{ users_using_rank|ordinal }} most used product out of {{ category_product_count }} products in category <a href="{% url 'products' country_code=country_code %}?category={{ product.category.id }}">{{ product.category.name|lower }}</a>.</h5>
        <h7><small class="text-muted">{{ users_using_percent }}% of members who use {{ product.category|lower }} are using this.</small></h7>
<!--        <h5>Average review rank:</h5>-->
    <hr>
        <h1>Reviews</h1>
        {% for review in product.review_set.all %}
        <blockquote class="blockquote"><p class="mb-0">{% include 'app/stars.html' with star_value=review.rating star_list=star_list only %} {{ review.review }}</p></blockquote>
        <footer class="blockquote-footer"><a href="{% url 'profile' country_code=country_code username=review.user.username %}">{{ review.user.username }}</a> | {{ review.user.profile.country }} | {{ review.last_updated|date:"M Y" }}</p></footer>
        {% endfor %}
        <hr/>
        {% if user.is_authenticated %}
            <h3>Add review</h3>
            {% if review_form_message %}
                <div class="alert alert-success" role="alert">{{ review_form_message }}</div>
            {% endif %}
            <form action="{% url 'product' country_code=country_code product_slug=product.name_slug %}" method="post">
                {% csrf_token %}
                {% crispy skin_type_form %}
                {% crispy review_form %}
                <button type="submit" class="btn btn-success" name="review_submit">Submit</button>
            </form>
        {% else %}
            <h3>Login to add your review</h3>
            <form action="{% url 'login' %}" method="post">
                {% csrf_token %}
                {% crispy authentication_form %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <button type="submit" class="btn btn-success">Login</button>
    <!--            <button type="button" class="btn btn-secondary">Forgotten password?</button>-->
            </form>
        {% endif %}
    </div>
</div>
{% endblock content %}

project/app/templates/app/products.html
{% extends "app/base.html" %}

{% block content %}
<h1>Products</h1>

{% include 'app/product_table.html' %}
{% endblock content %}

project/app/templates/app/profile.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>{{ username }}</h1>
<hr />
<h2>Products I'm using</h2>
<div class="row row-fluid">
<table class="table table-hover">
  <thead>
    <tr>
        <th scope="col">Category</th>
        <th scope="col">Brand</th>
        <th scope="col">Name</th>
    </tr>
  </thead>
  <tbody>
    {% url 'products' country_code=country_code as products_url %}
    {% for product in products_currently_using %}
    <tr>
        <td><a href="{{ products_url }}?category={{ product.category.id }}">{{ product.category.name }}</a></td>
        <td>{% if product.brand %}
                <a href="{{ products_url }}?brand={{ product.brand.id }}">{{ product.brand.name }}</a>
            {% endif %}
        </td>
        <td><a href="{% url 'product' country_code=country_code product_slug=product.name_slug %}">{{ product.name }}</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
<p>{{ products_currently_using.count }} product{{ products_currently_using.count|pluralize }}.</p>

<h2>Reviews</h2>
<div class="row row-fluid">
<table class="table table-hover">
  <thead>
    <tr>
        <th scope="col">Category</th>
        <th scope="col">Brand</th>
        <th scope="col">Name</th>
      <th scope="col">Rating</th>
      <th scope="col">Last Updated</th>
    </tr>
  </thead>
  <tbody>
    {% for review in reviews %}
    <tr>
        <td><a href="{{ products_url }}?category={{ review.product.category.id }}">{{ review.product.category.name }}</a></td>
        <td><a href="{{ products_url }}?brand={{ review.product.brand.id }}">{{ review.product.brand.name }}</a></td>
        <td><a href="{% url 'product' country_code=country_code product_slug=review.product.name_slug %}">{{ review.product.name }}</a></td>
        <td>{% include 'app/stars.html' with star_value=review.rating star_list=star_list only %}</td>
      <td>{{ review.last_updated }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
<p>{{ reviews.count }} review{{ reviews.count|pluralize }}.</p>
{% endblock content %}

project/app/templates/app/signup.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Sign Up</h1>
<div class="row row-fluid justify-content-center">
  <div class="col-sm-7">
    <form action="{% url 'signup' country_code %}" method="post">
      {% crispy user_form %}
      {% crispy profile_form %}
      <button type="submit" class="btn btn-success">Sign Up</button>
      <!--      <button type="button" class="btn btn-secondary">Forgotten password?</button>-->
    </form>
  </div>
</div>
{% endblock content %}